name: skynet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  cloud_firestore: ^4.13.6
  intl: ^0.18.1
  logger: ^2.5.0
  http: ^1.3.0
  webview_flutter: ^4.11.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  network_info_plus: ^5.0.2
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
